version: '3.8'

services:
  spencer-backend:
    build: .
    container_name: spencer-ai-backend
    restart: unless-stopped
    ports:
      - "8888:8888"
    volumes:
      - spencer-storage:/data/spencer-ai-storage
      - spencer-logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  spencer-storage:
    driver: local
  spencer-logs:
    driver: local