version: '3.8'

services:
  spencer-backend:
    build: .
    container_name: spencer-ai-backend
    restart: unless-stopped
    ports:
      - "8888:8888"
    environment:
      # Server Configuration
      SPENCER_HOST: "0.0.0.0"
      SPENCER_PORT: "8888"
      SPENCER_DEBUG: "False"
      
      # API Configuration
      CMS_API_BASE_URL: "${CMS_API_BASE_URL:-https://test.companiesms.co.uk}"
      CMS_API_TOKEN: "${CMS_API_TOKEN}"
      
      # MongoDB Configuration (YOUR VPS)
      MONGODB_URI: "${MONGODB_URI:-mongodb://root:CmsDeskAI%23mongod%4012@157.180.62.92:5567/default}"
      MONGODB_DATABASE: "${MONGODB_DATABASE:-spencer_ai}"
      
      # Redis Configuration (YOUR VPS)
      REDIS_URL: "${REDIS_URL:-redis://:CmsDeskAI%23redis%4012@157.180.62.92:5599/0}"
      REDIS_HOST: "${REDIS_HOST:-157.180.62.92}"
      REDIS_PORT: "${REDIS_PORT:-5599}"
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
      REDIS_DB: "${REDIS_DB:-0}"
      
      # Vector Service (YOUR VPS)
      VECTOR_SERVICE_URL: "${VECTOR_SERVICE_URL:-http://157.180.62.92:8001}"
      OLLAMA_URL: "${OLLAMA_URL:-http://157.180.62.92:11434}"
      OLLAMA_MODEL: "${OLLAMA_MODEL:-mxbai-embed-large}"
      
      # OpenRouter (Gemini)
      OPENROUTER_API_KEY: "${OPENROUTER_API_KEY}"
      OPENROUTER_BASE_URL: "${OPENROUTER_BASE_URL:-https://openrouter.ai/api/v1}"
      AI_MODEL: "${AI_MODEL:-google/gemini-flash-2.5}"
      
      # Groq (Whisper)
      GROQ_API_KEY: "${GROQ_API_KEY}"
      GROQ_BASE_URL: "${GROQ_BASE_URL:-https://api.groq.com/openai/v1}"
      GROQ_WHISPER_MODEL: "${GROQ_WHISPER_MODEL:-whisper-large-v3-turbo}"
      
      # Spencer File Manager (YOUR VPS)
      SPENCER_FILE_MANAGER_URL: "${SPENCER_FILE_MANAGER_URL:-http://157.180.62.92:8002}"
      FILEBROWSER_URL: "${FILEBROWSER_URL:-http://157.180.62.92:8090}"
      
      # File Storage
      FILE_STORAGE_PATH: "/data/spencer-ai-storage"
      FAISS_INDEX_PATH: "/data/spencer-ai-storage/faiss_indexes"
      
      # Rate Limiting
      RATE_LIMIT_REQUESTS: "${RATE_LIMIT_REQUESTS:-100}"
      RATE_LIMIT_PERIOD: "${RATE_LIMIT_PERIOD:-60}"
      
      # Logging
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      
    volumes:
      - spencer-storage:/data/spencer-ai-storage
      - spencer-logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  spencer-storage:
    driver: local
  spencer-logs:
    driver: local